"""
embed_data.py — DocStribe Patient Intelligence Dashboard
=========================================================
Reads patients_anonymized.xlsx, converts all 4 sheets to JSON, and
injects the data as window.EMBEDDED_DATA into index.html so the
dashboard loads instantly without requiring a file upload.

Usage:
    python embed_data.py
    python embed_data.py --excel custom_file.xlsx --html index.html

After running, open index.html in a browser — the dashboard will
auto-load with the embedded data. Users can still override it by
clicking "Load New File" to upload a different Excel file.
"""

import json
import os
import re
import sys
import argparse
from pathlib import Path
from datetime import date, datetime

# ── Auto-install openpyxl if missing ──────────────────────────────────────────
try:
    import openpyxl
except ImportError:
    print("[INFO] openpyxl not found -- installing...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "openpyxl", "-q"])
    import openpyxl
    print("[OK]  openpyxl installed\n")


SHEET_NAMES = ["Patients", "Visits", "Visit Actions", "Call History"]

# Marker used to locate/replace the injected block on re-runs
SCRIPT_ID = "embedded-data-block"


def serialise(val):
    """Convert a cell value to a JSON-serialisable Python type."""
    if val is None:
        return None
    if isinstance(val, (datetime, date)):
        return val.isoformat()
    if isinstance(val, float):
        # openpyxl sometimes gives int-valued floats
        return int(val) if val == int(val) else val
    return val


def sheet_to_rows(ws):
    """Convert a worksheet to a list of dicts (header row → keys)."""
    rows_iter = ws.iter_rows(values_only=True)
    try:
        headers = [str(h).strip() if h is not None else f"col_{i}"
                   for i, h in enumerate(next(rows_iter))]
    except StopIteration:
        return []

    result = []
    for row in rows_iter:
        # Skip completely empty rows
        if all(v is None for v in row):
            continue
        obj = {}
        for header, value in zip(headers, row):
            sv = serialise(value)
            if sv is not None:
                obj[header] = sv
        if obj:
            result.append(obj)
    return result


def read_excel(xlsx_path: Path) -> dict:
    """Parse the Excel file and return {sheet_name: [row_dicts]}."""
    print(f"Reading {xlsx_path}...")
    wb = openpyxl.load_workbook(xlsx_path, data_only=True, read_only=True)

    present = wb.sheetnames
    missing = [s for s in SHEET_NAMES if s not in present]
    if missing:
        print(f"\n[WARNING] sheet(s) not found in Excel — {missing}")
        print(f"    Available sheets: {present}\n")

    sheets = {}
    for name in SHEET_NAMES:
        if name not in present:
            sheets[name] = []
            continue
        ws = wb[name]
        rows = sheet_to_rows(ws)
        sheets[name] = rows
        size_kb = len(json.dumps(rows, ensure_ascii=False)) / 1024
        print(f"  [OK] {name:<20} {len(rows):>5} rows   (~{size_kb:.1f} KB)")

    wb.close()
    return sheets


def build_injection_block(sheets: dict) -> str:
    """Return the <script> tag string to inject into HTML."""
    json_str = json.dumps(sheets, ensure_ascii=False, separators=(",", ":"))
    size_kb = len(json_str.encode("utf-8")) / 1024
    print(f"\n  Total embedded JSON size: {size_kb:.1f} KB")
    return (
        f'<script id="{SCRIPT_ID}">\n'
        f"// Auto-generated by embed_data.py — DO NOT EDIT MANUALLY\n"
        f"// Re-run embed_data.py to refresh this block.\n"
        f"window.EMBEDDED_DATA={json_str};\n"
        f"</script>"
    )


def inject_into_html(html_path: Path, injection: str) -> None:
    """Remove any existing injection block and insert the new one."""
    with open(html_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Remove existing block (handles re-runs cleanly)
    content = re.sub(
        rf'<script id="{SCRIPT_ID}">.*?</script>\n?',
        "",
        content,
        flags=re.DOTALL,
    )

    # Insert directly before the main Babel script tag
    babel_marker = '<script type="text/babel">'
    if babel_marker not in content:
        print("\n[ERROR] could not find '<script type=\"text/babel\">' in index.html.")
        print("        Make sure you are running this against the DocStribe index.html.")
        sys.exit(1)

    content = content.replace(babel_marker, f"{injection}\n{babel_marker}", 1)

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[OK] Injected into: {html_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Embed Excel data into DocStribe index.html"
    )
    parser.add_argument(
        "--excel",
        default="patients_anonymized.xlsx",
        help="Path to Excel file (default: patients_anonymized.xlsx)",
    )
    parser.add_argument(
        "--html",
        default="index.html",
        help="Path to index.html (default: index.html)",
    )
    args = parser.parse_args()

    script_dir = Path(__file__).parent
    xlsx_path = Path(args.excel) if os.path.isabs(args.excel) else script_dir / args.excel
    html_path = Path(args.html)  if os.path.isabs(args.html)  else script_dir / args.html

    # Validate paths
    if not xlsx_path.exists():
        print(f"\n[ERROR] Excel file not found: {xlsx_path}")
        sys.exit(1)
    if not html_path.exists():
        print(f"\n[ERROR] HTML file not found: {html_path}")
        sys.exit(1)

    # Parse Excel
    sheets = read_excel(xlsx_path)

    total_rows = sum(len(v) for v in sheets.values())
    print(f"\n  Total rows across all sheets: {total_rows}")

    # Build injection
    injection = build_injection_block(sheets)

    # Inject into HTML
    print(f"\nInjecting into: {html_path}")
    inject_into_html(html_path, injection)

    print(
        f"\n[DONE]\n"
        f"   * {total_rows} rows from {len(sheets)} sheets embedded.\n"
        f"   * Open {html_path.name} in your browser -- dashboard loads instantly.\n"
        f"   * Users can still click 'Load New File' to upload a different Excel.\n"
    )


if __name__ == "__main__":
    main()
